### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by DanielDanielDanielDaniel** [xiaosongshine/MNT_RNN_Keras#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1339, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by {{node cu_dnnlstm_1/CudnnRNN}}with these attrs: [seed=87654321, dropout=0, input_mode="linear_input", T=DT_FLOAT, direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[cu_dnnlstm_1/CudnnRNN]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mian.py", line 211, in <module>
    encoder_model,decoder_model = load_model("enc1.h5",custom_objects={"my_acc":my_acc}),load_model("dec1.h5",custom_objects={"my_acc":my_acc})
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 550, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 305, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2732, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 216, in get_session
    [tf.is_variable_initialized(v) for v in candidate_vars])
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node cu_dnnlstm_1/CudnnRNN (defined at /usr/local/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py:517) with these attrs: [seed=87654321, dropout=0, input_mode="linear_input", T=DT_FLOAT, direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[cu_dnnlstm_1/CudnnRNN]]

Errors may have originated from an input operation.
Input Source operations connected to node cu_dnnlstm_1/CudnnRNN:
 cu_dnnlstm_1/ExpandDims_2 (defined at /usr/local/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py:488)	
 cu_dnnlstm_1/ExpandDims_1 (defined at /usr/local/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py:487)	
 cu_dnnlstm_1/transpose (defined at /usr/local/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py:484)	
 cu_dnnlstm_1/concat_1 (defined at /usr/local/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py:60)

**Comment by xiaosongshine** [comment]
tf 1.13.1 
keras 2.2.4
python 3.6
